#!/usr/bin/env node
/**
 * Stage-3 report for email-auth. Validates completeness (every checklist check has a verdict), computes
 * the rollup + an overall verdict, and writes a self-contained markdown report. Deterministic. Node only.
 *
 * Env: EMAILAUTH_VERDICTS (evaluate output), EMAILAUTH_CHECKLIST (checklist.json), EMAILAUTH_OUT
 *   (md report path, default ./email-auth-<domain>-<date>.md).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const ev = JSON.parse(readFileSync(process.env.EMAILAUTH_VERDICTS, "utf8"));
const checklist = JSON.parse(readFileSync(process.env.EMAILAUTH_CHECKLIST, "utf8"));
const verdicts = ev.verdicts ?? [];

// Completeness: every checklist check must have a verdict.
const got = new Set(verdicts.map((v) => v.id));
const missing = checklist.checks.filter((c) => !got.has(c.id)).map((c) => c.id);

const counts = { pass: 0, fail: 0, warn: 0, not_observable: 0 };
for (const v of verdicts) counts[v.status] = (counts[v.status] ?? 0) + 1;

// Verdict: any major fail → action needed; else any fail/warn → review; else ok.
const RANK = { info: 0, minor: 1, major: 2, critical: 3 };
const majorFail = verdicts.some((v) => v.status === "fail" && (RANK[v.severity] ?? 0) >= RANK.major);
const verdict = majorFail ? "ACTION NEEDED" : counts.fail || counts.warn ? "REVIEW" : "OK";

const stamp = new Date().toISOString().slice(0, 10);
const outPath = process.env.EMAILAUTH_OUT || `./email-auth-${(ev.domain || "domain").replace(/[^a-z0-9.-]/gi, "_")}-${stamp}.md`;
const ICON = { pass: "✅", fail: "❌", warn: "⚠️", not_observable: "➖" };

const lines = [
  `# Email authentication — ${ev.domain}`,
  "",
  `**Verdict: ${verdict}** · ${counts.pass} pass · ${counts.fail} fail · ${counts.warn} warn · ${counts.not_observable} n/a`,
  "",
  `Standard: ${ev.standard ?? checklist.standard}`,
  "",
  `| Check | Severity | Status | Detail |`,
  `|---|---|---|---|`,
];
for (const v of verdicts) lines.push(`| ${v.title} | ${v.severity} | ${ICON[v.status] ?? ""} ${v.status} | ${String(v.detail ?? "").replace(/\|/g, "\\|").slice(0, 120)} |`);
lines.push("");
lines.push(`<sub>Generated by Agent Flow · workflows/email-auth · DNS-only, deterministic.</sub>`);

mkdirSync(dirname(outPath) || ".", { recursive: true });
writeFileSync(outPath, lines.join("\n") + "\n", "utf8");

process.stdout.write(JSON.stringify({ domain: ev.domain, verdict, counts, report_md: outPath, incomplete: missing.length > 0, missing }, null, 2));
if (missing.length) {
  process.stderr.write(`report: integrity — ${missing.length} checks without a verdict: ${missing.join(", ")}\n`);
  process.exit(1);
}
