#!/usr/bin/env node
/**
 * Roundup stage for the security-pack meta-workflow. Reads the two nested sub-workflow summaries
 * (security-domain + security-repo) and writes one combined index.html linking both reports, with an
 * overall verdict = the worst of the two. Pure code, no LLM.
 *
 * Env: PACK_DOMAIN_SUMMARY, PACK_REPO_SUMMARY (the sub-workflows' result_pointers, i.e. their
 *      report-summary.json), PACK_TITLE, PACK_REPORT_OUT.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

function readJson(p) { try { return p && existsSync(p) ? JSON.parse(readFileSync(p, "utf8")) : null; } catch { return null; } }
// The sub-workflow's last stage output is its own report-summary.json (the {run, verdict, ...} object
// that report.mjs printed); it carries report_html + counts.
const dom = readJson(process.env.PACK_DOMAIN_SUMMARY);
const repo = readJson(process.env.PACK_REPO_SUMMARY);

const RANK = { "CRITICAL ISSUES OBSERVED": 5, "NON-COMPLIANT — critical issues observed": 5, "SIGNIFICANT GAPS": 4, "SIGNIFICANT GAPS — major issues observed": 4, "NEEDS ATTENTION": 3, "MOSTLY OK — review warnings": 2, "NO BLOCKING ISSUES OBSERVED": 1 };
const parts = [
  dom && { name: "Web security (domain)", subject: dom.domain, ...dom },
  repo && { name: "Source security (repo)", subject: repo.repo, ...repo },
].filter(Boolean);
const overall = parts.reduce((w, p) => (RANK[p.verdict] ?? 0) > (RANK[w] ?? 0) ? p.verdict : w, "NO BLOCKING ISSUES OBSERVED");

const esc = (x) => String(x ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const cls = (v) => (/critical|non-compliant/i.test(v) ? "v-crit" : /significant/i.test(v) ? "v-major" : /needs/i.test(v) ? "v-attn" : /mostly/i.test(v) ? "v-warn" : "v-ok");
const cards = parts.map((p) => `<a class="part ${cls(p.verdict)}" href="${esc(p.report_html)}">
  <div class="pname">${esc(p.name)}</div><div class="psub">${esc(p.subject || "")}</div>
  <div class="pv">${esc(p.verdict)}</div>
  <div class="pc">pass ${p.counts?.pass ?? "?"} · fail ${p.counts?.fail ?? "?"} · warn ${p.counts?.warn ?? "?"} · score ${p.score ?? "—"}%</div>
  <div class="plink">open report →</div></a>`).join("\n");

const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Security pack — ${esc(process.env.PACK_TITLE || "audit")}</title><style>
:root{--ink:#1a1d24;--mut:#5c6470;--line:#e4e7ec;--bg:#f7f8fa;--card:#fff}*{box-sizing:border-box}
body{font:15px/1.55 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:var(--ink);background:var(--bg);margin:0}
.wrap{max-width:880px;margin:0 auto;padding:40px 20px}h1{font-size:24px;margin:0 0 4px}.sub{color:var(--mut);font-size:13px;margin-bottom:20px}
.verdict{display:inline-block;font-weight:700;padding:10px 16px;border-radius:10px;margin-bottom:22px}
.v-crit{background:#fde8e8;color:#b42318}.v-major{background:#fdeede;color:#b54708}.v-attn{background:#fef6e0;color:#a16207}.v-warn{background:#fffbeb;color:#92740a}.v-ok{background:#e6f6ec;color:#067647}
.parts{display:flex;flex-wrap:wrap;gap:14px}.part{flex:1;min-width:300px;text-decoration:none;color:inherit;background:var(--card);border:1px solid var(--line);border-left-width:5px;border-radius:12px;padding:18px 20px}
.part.v-crit{border-left-color:#b42318}.part.v-major{border-left-color:#b54708}.part.v-attn{border-left-color:#a16207}.part.v-warn{border-left-color:#92740a}.part.v-ok{border-left-color:#067647}
.pname{font-weight:700;font-size:16px}.psub{color:var(--mut);font-size:12px;margin-bottom:8px}.pv{font-weight:600;margin-bottom:4px}.pc{font-size:12.5px;color:var(--mut)}.plink{margin-top:10px;color:#155eef;font-size:13px;font-weight:600}
footer{color:var(--mut);font-size:12px;margin-top:28px}</style></head><body><div class="wrap">
<h1>Security pack</h1><div class="sub">${esc(process.env.PACK_TITLE || "")} · generated ${esc(new Date().toISOString())} · ${parts.length} nested audits</div>
<div class="verdict ${cls(overall)}">Overall: ${esc(overall)}</div>
<div class="parts">${cards || "<p>(no sub-reports produced)</p>"}</div>
<footer>Generated by Agent Flow · workflows/security-pack — a meta-workflow composing nested sub-workflows (the <code>· workflow</code> stage). Each card links to the full self-contained report.</footer></div></body></html>`;

const outPath = resolve(process.env.PACK_REPORT_OUT || `./security-pack-${new Date().toISOString().slice(0, 10)}.html`);
writeFileSync(outPath, html, "utf8");
process.stdout.write(JSON.stringify({ overall, parts: parts.map((p) => ({ name: p.name, verdict: p.verdict, score: p.score, report_html: p.report_html })), index_html: outPath }, null, 2));
