#!/usr/bin/env node
/**
 * Stage-7 finalize for knowledge-build. Builds the top-level `index.md` (architecture map + entity links
 * grouped by area), renders `relations.md` from the LLM-derived relations list, and writes/advances
 * `manifest.json` (the reference commit + per-entity hashes + doc paths) so `update` runs know what to
 * re-document. The relations list is also kept as JSON — the seed for a future graph-DB export. Node only.
 *
 * Env: KB_CONFIG (resolve output), KB_ENTITIES (validate result — the entities items), KB_RELATIONS
 *   (relate step output, optional).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const cfg = JSON.parse(readFileSync(process.env.KB_CONFIG, "utf8"));
const items = JSON.parse(readFileSync(process.env.KB_ENTITIES, "utf8"));
const outDir = cfg.out_dir;
mkdirSync(outDir, { recursive: true });

const rel = (p) => relative(outDir, p).split(sep).join("/");

// ---- relations (tolerant of shape: {relations:[…]} or a bare array) ----
let relations = [];
if (process.env.KB_RELATIONS && existsSync(process.env.KB_RELATIONS)) {
  try {
    const r = JSON.parse(readFileSync(process.env.KB_RELATIONS, "utf8"));
    relations = Array.isArray(r) ? r : Array.isArray(r.relations) ? r.relations : [];
  } catch {
    /* leave empty */
  }
}
if (relations.length) {
  const relLines = ["# Relationships", "", "| From | Relation | To |", "|---|---|---|"];
  for (const e of relations) relLines.push(`| ${e.from ?? "?"} | ${e.kind ?? "related-to"} | ${e.to ?? "?"} |`);
  writeFileSync(join(outDir, "relations.md"), relLines.join("\n") + "\n", "utf8");
  writeFileSync(join(outDir, "relations.json"), JSON.stringify({ relations }, null, 2), "utf8");
}

// ---- index.md (grouped by area) ----
const byArea = new Map();
for (const it of items) {
  const a = it.data.area;
  (byArea.get(a) ?? byArea.set(a, []).get(a)).push(it);
}
const idx = [`# Knowledge base`, "", `Generated by Agent Flow · \`knowledge-build\` (${cfg.mode}) · ref \`${cfg.ref ?? "n/a"}\` · ${items.length} entities.`, ""];
if (relations.length) idx.push(`See [relations.md](relations.md) for the relationship graph.`, "");
for (const area of [...byArea.keys()].sort()) {
  idx.push(`## ${area}`, "");
  for (const it of byArea.get(area).sort((a, b) => a.data.entity_id.localeCompare(b.data.entity_id))) {
    const d = it.data;
    idx.push(`- [${d.entity_id}](${rel(d.doc_path)}) — _${d.kind}_${d.summary ? ` · ${String(d.summary).replace(/\s+/g, " ").slice(0, 100)}` : ""} (${d.files.length} file${d.files.length === 1 ? "" : "s"})`);
  }
  idx.push("");
}
writeFileSync(join(outDir, "index.md"), idx.join("\n"), "utf8");

// ---- manifest (advance the reference) ----
// In update mode, merge: keep manifest entries not re-documented this run, overwrite the ones that were.
let prior = [];
if (cfg.mode === "update" && existsSync(cfg.manifest_path)) {
  try {
    prior = JSON.parse(readFileSync(cfg.manifest_path, "utf8")).entities ?? [];
  } catch {
    /* ignore */
  }
}
const nowDocumented = new Map(items.map((it) => [it.id, { id: it.id, entity_id: it.data.entity_id, area: it.data.area, files: it.data.files, content_hash: it.data.content_hash, doc_path: it.data.doc_path }]));
const merged = new Map(prior.map((e) => [e.id, e]));
for (const [k, v] of nowDocumented) merged.set(k, v);
const manifest = { ref: cfg.ref, generated_at: new Date().toISOString().replace(/\.\d{3}Z$/, "Z"), mode: cfg.mode, out_dir: outDir, entities: [...merged.values()] };
writeFileSync(cfg.manifest_path, JSON.stringify(manifest, null, 2), "utf8");

process.stdout.write(JSON.stringify({ index: join(outDir, "index.md").split("\\").join("/"), entities: items.length, relations: relations.length, manifest: cfg.manifest_path, ref: cfg.ref }, null, 2));
